name: Deploy to Zeabur
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: npm install
        
    - name: Build
      run: npm run build
      env:
        CI: true
        
    - name: Deploy to Zeabur
      uses: zeabur/cli-action@v1
      env:
        ZEABUR_TOKEN: ${{ secrets.ZEABUR_TOKEN }}
      with:
        project: chat
        service: web
